import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true, args: ['--no-proxy-server'] });
const page = await (await browser.newContext({ viewport: { width: 1280, height: 800 } })).newPage();
await page.goto('http://localhost:4000/about.html', { waitUntil: 'networkidle' });
await page.waitForTimeout(800);
let stagePersp = await page.$eval('.story-stage', el => getComputedStyle(el).perspective);
let trackStyle = await page.$eval('.story-track', el => getComputedStyle(el).transformStyle);
let gradBg = await page.$eval('.story-backdrop__gradient', el => getComputedStyle(el).backgroundImage);
console.log(`PERSPECTIVE ${stagePersp} TRACK_STYLE ${trackStyle}`);
console.log(`GRAD_BG ${gradBg.slice(0,120)}`);
await page.mouse.wheel(0, 600);
await page.waitForTimeout(900);
let sceneTx = await page.$eval('.story-scene:nth-child(2)', el => el.style.transform);
let layerTx = await page.$eval('.story-backdrop__gradient', el => el.style.transform);
console.log(`SCENE_3D ${sceneTx}`);
console.log(`LAYER_3D ${layerTx}`);
await page.screenshot({ path: `M:\\money\\dropshipping\\verify-out\\about-3d-1280.png`, fullPage: false });
console.log('3D_SCREENSHOT done');
await browser.close();
